### ISSUE TITLE
Removal of codename from IMultipleChoiceOption

### ISSUE THREAD

**Issue by jfeyers** [kontent-ai/management-sdk-js#107]
Within commit 3a59a45, the codename property was removed from IMultipleChoiceOption in \models\elements\content-type-element.models.d.ts. I think this was done in error because I see the codename property was added to the IElementShared interface which is inherited by most other interfaces within that file. However IMultipleChoiceOption does not inherit from IElementShared which makes me think it was done in error.

We use codename within our options to define content types like so:
`options: [
        { name: 'Basic', codename: 'basic' },
        { name: 'Email Only', codename: 'email_only' },
        { name: 'Visit', codename: 'visit' },
        { name: 'Interest', codename: 'interest' },
        { name: 'Careers', codename: 'careers' },
        { name: 'Inquiry (without Locations)', codename: 'inquiry_without_locations' },
        { name: 'Inquiry (with Locations)', codename: 'inquiry_with_locations' },
        { name: 'Submission', codename: 'submission' },
        { name: 'Service', codename: 'service' },
      ],`
Now I can not longer do this which breaks much of our code.

Please let me know if this was done in error and if so, when will it be fixed?

**Comment by jfeyers** [comment]
Thanks for fixing this. When will a new NPM release be created with this fix?

**Comment by Enngage** [comment]
Hey @jfeyers, we expect to release this later this week along with some further product changes (especially the rename of project to environments)
