### ISSUE TITLE
Add support for Collection property in Assets

### ISSUE THREAD

**Issue by AdamZ-Kontent** [kontent-ai/management-sdk-js#115]
### Motivation

New collection property will be added to the Asset models in management api, this SDK should support it too

### Proposed solution

Extend Asset models with a new Collection reference property

After completion, please update request code samples in MAPI documentation

### Additional context

early access release date 14.6.2023
[docs](https://kontent.ai/learn/reference/openapi/management-api-v2/#section/Asset-object)
the new Collection property will be an object containing a nullable reference to a collection
example of the property in json:  `"collection": {
       "reference": { "id": "00000000-0000-0000-0000-000000000000" }
  }`
[.NET PR](https://github.com/kontent-ai/management-sdk-net/pull/248)

**Comment by gormal** [comment]
Already merged.
