### ISSUE TITLE
Add method to managementClient to retrieve asset using codename 

### ISSUE THREAD

**Issue by harsha121** [kontent-ai/management-sdk-js#124]
### Motivation

Why is this feature required? What problems does it solve?
We want to fetch asset using codename with managementClient as mentioned in the below api.
https://kontent.ai/learn/docs/apis/openapi/management-api-v2/#operation/retrieve-an-asset

### Proposed solution

An ideal solution for the above problems.
Please add managementClient.viewAsset().byCodeName() to fetch  asset using codename 

### Additional context

Add any other context, screenshots, or reference links about the feature request here.

**Comment by Enngage** [comment]
Hey @harsha121,

I've just released this in v `5.5.0`
