### ISSUE TITLE
Asset folder codenames

### ISSUE THREAD

**Issue by matus12** [kontent-ai/management-sdk-js#154]
### Motivation

We're adding codenames as a reference for asset folders, so assets can be inserted into correct folder referenced by codename.

### Proposed solution

Add codename as a reference for asset folders to request/response

-  Retrieve asset folders
- Add asset folders
- Modify asset folders
- Add an asset
- Upsert an asset

### Additional context

EN-207

**Comment by Enngage** [comment]
PR https://github.com/kontent-ai/management-sdk-js/pull/155
