### ISSUE TITLE
Add support for default value in Linked Items and Assets content type element

### ISSUE THREAD

**Issue by RadoslavK** [kontent-ai/management-sdk-js#84]
### Motivation

We have added support for default values in MAPI for 2 other elements: linked items and assets.

### Proposed solution

Extend the request and response model of content type element for Assets and Linked Items similarly to other elements like text, number, or date time. The same constraints apply. The shape is `{ default: { global: { value } } }`, where the whole `default` object can be null. Otherwise, it must be of the exact shape.

Value types:
- Linked items - Array of ManageApiReference
- Assets - Array of ManageApiReference

It should be possible to create or replace content type with these elements and default values set. It should also be possible to patch the default value. Either by replacing it as a whole or inserting it into the list.

### Additional context

This feature will be released at the end of August but the SDK does not block it.

**Comment by Simcsa** [comment]
The asset default value will be released 31.8.
The linked item default value will be released 14.9.

**Comment by Enngage** [comment]
Released in `3.3.0`
