### ISSUE TITLE
Extend Taxonomy type element with name field

### ISSUE THREAD

**Issue by micheltol** [kontent-ai/management-sdk-js#86]
### Motivation

I am  using the [Kontent CLI](https://github.com/kontent-ai/cli) for migrating / modifying content types and I would like to add an existing taxonomy to my content type. The management V2 allows me to add this taxonomy element via the [Modify a content type](https://kontent.ai/learn/reference/management-api-v2/#operation/modify-a-content-type). 

Unfortunately this endpoint doesn't allow me to specify the element name for taxonomy elements. It will result in a taxonomy element name which is identical to the taxonomy name itself. So after running the migration scripts I manually have to navigate through the Content types in the UI and update the elements to give them a proper name.

### Why is this feature required? What problems does it solve?

We would like to give the taxonomy element in a content item an useful name which matches the purpose of the field instead of the generic taxonomy name.

### Proposed solution

Extend the [Taxonomy-type-element](https://kontent.ai/learn/reference/management-api-v2/#section/Taxonomy-type-element) to support the name field, just like the [Text-type-element](https://kontent.ai/learn/reference/management-api-v2/#section/Text-type-element). If the name field is not provided fall back to the current behavior (the taxonomy name).

In the attached screenshot, the taxonomy element name 'Navigation Topic' can't be set via the Management API v2. If we would like to achieve an element like the screenshot an extra manual step in the UI is required.

![image](https://user-images.githubusercontent.com/2670832/192562638-f25b5cd1-bb5b-44e4-9a93-ca8f9234ca98.png)

**Comment by Enngage** [comment]
Hi @micheltol,

I've raised the issue internally as I'm not sure why the `name` of the taxonomy elements cannot be updated via API. I will update you once get some more information. 

I might close this issue at some point as it's not really related to this SDK specifically, but rather it's a current limitation of our API. Once this feature comes to API, we will quickly add support for it to this SDK :-)

**Comment by micheltol** [comment]
Hi @Enngage thank you for the update. I was not really sure were to raise the question / request so I thought I would give it a go overhere :)
