### ISSUE TITLE
Failing mapping for type issues with listProjectValidationIssues()

### ISSUE THREAD

**Issue by pokornyd** [kontent-ai/management-sdk-js#87]
### Brief bug description

The SDK uses a single model called `ProjectValidationIssueModel` for mapping individual issues returned from [List project validation results](https://kontent.ai/learn/reference/management-api-v2/#operation/list-project-validation-results) MAPI endpoint, which is called by the method in question.

```
    export class ProjectValidationIssueModel {
        constructor(
            public issue_type: ProjectContracts.ProjectValidationIssueType,
            public item: ProjectVariantContentItemModel,
            public language: ProjectVariantLanguageModel,
            public issues: ProjectIssueModel[]
        ) {}
    }
```
However, objects representing `variant_issue` and `type_issue` are different from each other (see responses in the endpoint docs), which the [mapper doesn't take into account](https://github.com/kontent-ai/management-sdk-js/blob/master/lib/mappers/project-mapper.ts#L16), resulting in type issues being processed as undefined and consequently raising an uncaught error.

### Repro steps

1. Create a type_issue in your project (e.g. reference a taxonomy in a content type, then subsequently delete it)
2. Run a project validation and get its ID
3. Wait for the validation to finish, then feed its ID to `listProjectValidationIssues().byTaskId()` method and log the response
4. Observe the logged error

### Expected behavior

The method should map both issue types accordingly.

### Test environment

Simple HTML with JS, tested with latest SDK version (3.3.0)

### Additional context

The SDK already implements both `ProjectTypeIssueModel` and `ProjectVariantIssueModel`. The latter is mostly a duplication of `ProjectValidationIssueModel`, minus the issue_type, so the mapping logic could theoretically be updated to only use the first two models.

### Screenshots

![image](https://user-images.githubusercontent.com/52500882/192621637-3846c550-08a6-4086-b55c-45023550c3eb.png)

**Comment by micheltol** [comment]
Am I correct @Enngage  when I assume that `ProjectModels.ProjectValidationIssueModel` replaced by `ProjectModels.ProjectValidationVariantIssueModel` ?

**Comment by Enngage** [comment]
@micheltol, yeah, there are now 2 separate models `ProjectModels.ProjectValidationVariantIssueModel` and `ProjectModels.ProjectValidationTypeIssueModel`.
