### ISSUE TITLE
Cannot read properties of undefined (reading 'queryService')

### ISSUE THREAD

**Issue by msrcodes** [kontent-ai/management-sdk-js#88]
### Brief bug description

Hey there, I'm working on an abstraction over the Management SDK to streamline my workflow

I'm trying to make a singular function, `update`, that will be able to update a content type, snippet or taxonomy with relevant data whilst maintaining type-safety

However I'm getting an error from inside of the Management SDK

I've thrown the code snippets and error message into a Gist

Any thoughts / questions / suggestions would be super 🚀 Thanks!

### Repro steps

https://gist.github.com/msrcodes/80fc4b5325d266f638c3e45f4c153ab0

### Expected behavior

I'm trying to make a singular function, `update`, that will be able to update a content type, snippet or taxonomy with relevant data whilst maintaining type-safety

### Test environment

 - Platform/OS: TypeScript
 - Browser: N/A
 - Version: latest

### Additional context

Using Kontent.ai's in-site chat support, they said "We agreed that the error is too generic."

**Comment by Enngage** [comment]
Hey @msrcodes,

We can't really support you with a custom code, but if you make **as simplified as possible** reproduction on https://stackblitz.com, I'll have a look and see what's might be going on.

**Comment by msrcodes** [comment]
Hey @Enngage :)

I hope this helps - [StackBlitz](https://stackblitz.com/edit/typescript-yzutga?devToolsHeight=33&file=index.ts) - you can see the error in the console

Any indication as to why this is happening or more helpful error message would be super

**Comment by Enngage** [comment]
Hey, the stackblitz is not working for me - 

![abc](https://user-images.githubusercontent.com/7137351/194297277-4fd8bd27-91c8-4f17-996e-cbdf46615f2c.png)

**Comment by msrcodes** [comment]
> Hey, the stackblitz is not working for me -
> 
> ![abc](https://user-images.githubusercontent.com/7137351/194297277-4fd8bd27-91c8-4f17-996e-cbdf46615f2c.png)

Refresh now, needed an `index.html` adding
