### ISSUE TITLE
Workflow object is missing in the Language variant object

### ISSUE THREAD

**Issue by maartenhvdh** [kontent-ai/management-sdk-js#99]
### Brief bug description

When you call `viewLanguageVariant` you are missing the workflow object.

The `workflow_stepobject` is deprecated and is replace with workflow see https://kontent.ai/learn/reference/openapi/management-api-v2/#section/Language-variant-object

`workflow` property is inside the response but is missing in the model `ContentItemLanguageVariant` and `ContentItemLanguageWithComponentsVariant`
See https://github.com/kontent-ai/management-sdk-js/edit/master/lib/models/language-variants/language-variant.models.ts

### Repro steps

1. Call viewLanguageVariant
2. Response misses Workflow object

### Expected behavior

Be able to get workflow object like in the response

```
"workflow": {
    "workflow_identifier": {
        "id": "06ea628e-4ec7-4991-91e4-1412995151ee"
      },
     "step_identifier": {
         "id": "dc87d7cf-424b-4b89-9519-c9f79a3458b7"
      }
},
```

### Test environment

 - Platform/OS: JS SDK
 - Browser: n/a
 - Version: 4.0.0

### Screenshots

Add links to screenshots, if possible.

**Comment by Nickm615** [comment]
I took a look at the response from `viewLangVar` and found something interesting:
The `_raw` response object contains both the outdated `workflow_step` and the `workflow` object like this
`workflow_step: { id: '36892c71-65ba-4fed-a1ab-7753f4fa4faa' },
 workflow: { workflow_identifier: [Object], step_identifier: [Object] },`

but the regular response object has

`workflowStep: ReferenceObject {
    codename: undefined,
    externalId: undefined,
    id: '36892c71-65ba-4fed-a1ab-7753f4fa4faa'
  },`

I'm actually not sure the difference between the regular and raw response object, @Enngage could you help shed some light?

**Comment by Enngage** [comment]
@Nickm615, the `_raw` object contains unchanged response you receive from the API. This is there so you could potentially access data that is not yet available in the SDK (as there is always a delay when new features comes to API and when it's implemented to SDK + some people might be using older versions with no short-term possibility to upgrade). 

Response object is what SDK processes and provides interfaces for.

**Comment by Nickm615** [comment]
Thanks for clarity @Enngage, I didn't update the language variant interfaces when I made the workflow update, working on it now.

**Comment by Nickm615** [comment]
@Enngage PR open and waiting for review https://github.com/kontent-ai/management-sdk-js/pull/102

**Comment by Enngage** [comment]
Merged in https://github.com/kontent-ai/management-sdk-js/commit/3cba1ec513961dc9a8d25939f4880a576fca2bdc
